// Code generated by jetted for TypeScript v0.2.0

export interface CustomOverridesOverrideTypeDiscriminatorBaz {
  foo: "baz";
}

export interface CustomOverrides {
  override_elements_container: string[];
  override_type_discriminator: any;
  override_type_enum: any;
  override_type_expr: any;
  override_type_properties: any;
  override_values_container: { [key: string]: string };
}
