// Code generated by jetted for TypeScript v0.2.0

export type EnumCollisionsFooBar =
  | "x"
  | "y"

export interface EnumCollisionsFoo {
  bar: EnumCollisionsFooBar;
}

export type EnumCollisionsFooBar0 =
  | "x"
  | "y"

export interface EnumCollisions {
  foo: EnumCollisionsFoo;
  foo_bar: EnumCollisionsFooBar0;
}
