// Code generated by jetted for TypeScript v0.2.0

export interface TypeCollisionsFooBar {
  x: boolean;
}

export interface TypeCollisionsFoo {
  bar: TypeCollisionsFooBar;
}

export interface TypeCollisionsFooBar0 {
  x: string;
}

export interface TypeCollisions {
  foo: TypeCollisionsFoo;
  foo_bar: TypeCollisionsFooBar0;
}
