// Code generated by jetted for TypeScript v0.2.0

export type NullableDiscriminator0 = NullableDiscriminatorBar | NullableDiscriminatorQuux;

export interface NullableDiscriminatorBar {
  foo: "bar";
  baz: string;
}

export interface NullableDiscriminatorQuux {
  foo: "quux";
  quuz: string;
}

export type NullableDiscriminator = (NullableDiscriminator0 | null);
