// Code generated by jetted for TypeScript v0.2.0

export interface NullableProperties0 {
  bar: string;
  baz: boolean[];
  foo: boolean;
  quux: boolean[];
}

export type NullableProperties = (NullableProperties0 | null);
