// Code generated by jetted for TypeScript v0.2.0

export interface InitialismsNestedIdInitialism {
  json: string;
  normalword: string;
}

export interface Initialisms {
  http: string;
  id: string;
  nested_id_initialism: InitialismsNestedIdInitialism;
  utf8: string;
  word_with_embedded_id_initialism: string;
  word_with_trailing_initialism_id: string;
}
